---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: anyapplications.dcp.hiro.io
spec:
  group: dcp.hiro.io
  names:
    kind: AnyApplication
    listKind: AnyApplicationList
    plural: anyapplications
    singular: anyapplication
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: AnyApplication is the Schema for the anyapplications API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: AnyApplicationSpec defines the desired state of AnyApplication.
            properties:
              placementStrategy:
                properties:
                  strategy:
                    type: string
                required:
                - strategy
                type: object
              recoverStrategy:
                properties:
                  maxRetries:
                    type: integer
                  tolerance:
                    type: integer
                type: object
              source:
                description: Foo is an example field of AnyApplication. Edit anyapplication_types.go
                  to remove/update
                properties:
                  helm:
                    properties:
                      chart:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        description: Parameters is a list of Helm parameters which
                          are passed to the helm template command upon manifest generation
                        items:
                          properties:
                            forceString:
                              description: ForceString determines whether to tell
                                Helm to interpret booleans and numbers as strings
                              type: boolean
                            name:
                              description: Name is the name of the Helm parameter
                              type: string
                            value:
                              description: Value is the value for the Helm parameter
                              type: string
                          type: object
                        type: array
                      releaseName:
                        type: string
                      repository:
                        type: string
                      skipCrds:
                        description: SkipCrds skips custom resource definition installation
                          step (Helm's --skip-crds)
                        type: boolean
                      values:
                        type: string
                      version:
                        type: string
                    required:
                    - chart
                    - namespace
                    - repository
                    - version
                    type: object
                type: object
              syncPolicy:
                properties:
                  automated:
                    description: Automated will keep an application synced to the
                      target revision
                    properties:
                      allowEmpty:
                        description: 'AllowEmpty allows apps have zero live resources
                          (default: false)'
                        type: boolean
                      prune:
                        description: 'Prune specifies whether to delete resources
                          from the cluster that are not found in the sources anymore
                          as part of automated sync (default: false)'
                        type: boolean
                      selfHeal:
                        description: 'SelfHeal specifes whether to revert resources
                          back to their desired state upon modification in the cluster
                          (default: false)'
                        type: boolean
                    type: object
                  retry:
                    description: Retry controls failed sync retry behavior
                    properties:
                      backoff:
                        description: Backoff controls how to backoff on subsequent
                          retries of failed syncs
                        properties:
                          duration:
                            description: Duration is the amount to back off. Default
                              unit is seconds, but could also be a duration (e.g.
                              "2m", "1h")
                            type: string
                          factor:
                            description: Factor is a factor to multiply the base duration
                              after each failed retry
                            format: int64
                            type: integer
                          maxDuration:
                            description: MaxDuration is the maximum amount of time
                              allowed for the backoff strategy
                            type: string
                        type: object
                      limit:
                        description: Limit is the maximum number of attempts for retrying
                          a failed sync. If set to 0, no retries will be performed.
                        format: int64
                        type: integer
                    type: object
                  syncOptions:
                    description: Options allow you to specify whole app sync-options
                    items:
                      type: string
                    type: array
                type: object
              zones:
                type: integer
            required:
            - source
            - zones
            type: object
          status:
            description: AnyApplicationStatus defines the observed state of AnyApplication.
            properties:
              ownership:
                properties:
                  epoch:
                    format: int64
                    type: integer
                  owner:
                    type: string
                  placements:
                    items:
                      properties:
                        nodeAffinity:
                          items:
                            type: string
                          type: array
                        zone:
                          type: string
                      required:
                      - zone
                      type: object
                    type: array
                  priority:
                    format: int64
                    type: integer
                  state:
                    type: string
                required:
                - epoch
                - owner
                - priority
                - state
                type: object
              zones:
                items:
                  properties:
                    chartVersion:
                      type: string
                    conditions:
                      items:
                        properties:
                          lastTransitionTime:
                            format: date-time
                            type: string
                          msg:
                            type: string
                          reason:
                            type: string
                          retryAttempt:
                            type: integer
                          status:
                            type: string
                          type:
                            type: string
                          zoneId:
                            type: string
                        required:
                        - lastTransitionTime
                        - status
                        - type
                        - zoneId
                        type: object
                      type: array
                    version:
                      format: int64
                      type: integer
                    zoneId:
                      type: string
                  required:
                  - version
                  - zoneId
                  type: object
                type: array
            required:
            - ownership
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
