# This rule is not used by the project anyapplication-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dcp.hiro.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: anyapplication-controller
    app.kubernetes.io/managed-by: kustomize
  name: anyapplication-editor-role
rules:
- apiGroups:
  - dcp.hiro.io
  resources:
  - anyapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dcp.hiro.io
  resources:
  - anyapplications/status
  verbs:
  - get
