# This rule is not used by the project anyapplication-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dcp.hiro.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: anyapplication-controller
    app.kubernetes.io/managed-by: kustomize
  name: anyapplication-viewer-role
rules:
- apiGroups:
  - dcp.hiro.io
  resources:
  - anyapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dcp.hiro.io
  resources:
  - anyapplications/status
  verbs:
  - get
