replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
secretKey: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

serviceMonitorEnabled: true

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

tolerations: []

# nodeSelector:  

resources:
  requests:
    cpu: 1
    memory: 500Mi
  limits:
    cpu: 1
    memory: 500Mi

services:
  type: ClusterIP
  # the port for the API endpoint
  api:
    port: 9000
  # the port for the HTTP health endpoint
  health:
    port: 8081
  # the port for the metrics endpoint    
  metrics:
    port: 8085
    secure: false

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthz
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5

configuration:
  peers: []
  runtime:
    zone: zone
    operationalPollDuration: 5s
    syncPollDuration: 60s
    chartVersionPollDuration: 60s    
    defaultSyncTimeout: 180s
    defaultUndeployTimeout: 180s
  api:
    bind_address: :9000
  logging:
    default_level: info
    components:
      SyncManager: error
      GitOpsEngine: error
      ClusterCache: error
      Controller: error
      Jobs: info
      API: info
      Helm: error
