apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
    # the port for the API endpoint
    - port: {{ .Values.services.api.port }}
      {{- if .Values.services.api.nodePort }}
      nodePort: {{ .Values.services.api.nodePort }}
      {{- end }}
      protocol: TCP
      name: api
    # the port for the HTTP health endpoint
    - port: {{ .Values.services.health.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
